name: "DiYaZeN's Podcast Feed Generator"
author: "DiYaZeN"
description: "Generate a podcast feed from a folder of audio files"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: "Email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Name"
    required: true
    default: ${{ github.actor }}
